"""KasKorsou Scraper — Configuration"""

SUPABASE_URL = "https://tbfjlfnahdqfbnpszyyj.supabase.co"
# Service role key voor writes — Supabase dashboard > Settings > API > service_role
SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRiZmpsZm5haGRxZmJucHN6eXlqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NTg5Mjk0MSwiZXhwIjoyMDgxNDY4OTQxfQ.zCtXe-AXWTeECtSENoqw4nJmlK3KyArWfXScnX1ReTA"

SOURCES = {
    "remax": {
        "name": "RE/MAX Bonbini",
        "base_url": "https://www.realestate-curacao.com",
        "listings_url": "https://www.realestate-curacao.com/nl/woningen/koopwoningen/",
        "type": "traditional",
        "priority": 9,
    },
    "sunbelt": {
        "name": "Sunbelt Realty",
        "base_url": "https://www.sunbelt.an",
        "listings_url": "https://www.sunbelt.an/for-sale",
        "type": "traditional",
        "priority": 9,
    },
    "century21": {
        "id": "century21",
        "name": "Century 21 Curacao",
        "base_url": "https://century21numberone.com",
        "listings_url": "https://century21numberone.com/en/s/for-sale/",
        "type": "traditional",
        "priority": 8,
    },
    "era": {
        "name": "ERA Curacao",
        "base_url": "https://www.eracuracao.com",
        "listings_url": "https://www.eracuracao.com/listings",
        "type": "traditional",
        "priority": 7,
    },
    "facebook": {
        "id": "facebook",
        "name": "Facebook Marketplace",
        "base_url": "https://www.facebook.com",
        "listings_url": "https://www.facebook.com/marketplace/curacao/propertyrentals",
        "type": "claude_computer_use",
        "priority": 10,
    },
    "athome": {
        "id": "athome",
        "name": "At Home Curaçao",
        "base_url": "https://athomecuracao.com",
        "listings_url": "https://athomecuracao.com/kopen/",
        "type": "traditional",
        "priority": 9,
    },
    "caresto": {
        "id": "caresto",
        "name": "Caresto Real Estate",
        "base_url": "https://www.caresto.com",
        "listings_url": "https://www.caresto.com/wp-json/wp/v2/caresto_property",
        "type": "traditional",
        "priority": 8,
    },
    "livinggoed": {
        "id": "livinggoed",
        "name": "Livinggoed Real Estate",
        "base_url": "https://livinggoed.com",
        "listings_url": "https://livinggoed.com/property-sitemap.xml",
        "type": "traditional",
        "priority": 8,
    },
    "new_winds_realty": {
        "id": "new_winds_realty",
        "name": "New Winds Realty",
        "base_url": "https://www.newwindsrealty.com",
        "listings_url": "https://www.newwindsrealty.com/wp-json/wp/v2/properties",
        "type": "traditional",
        "priority": 8,
    },
    "keller_williams": {
        "id": "keller_williams",
        "name": "Keller Williams Curacao",
        "base_url": "https://kw-curacao.com",
        "listings_url": "https://kw-curacao.com/listings",
        "type": "traditional",
        "priority": 8,
    },
    "curahousecare": {
        "id": "curahousecare",
        "name": "CuraHouseCare",
        "base_url": "https://curahousecare.com",
        "listings_url": "https://curahousecare.com/wp-json/wp/v2/objecten",
        "type": "traditional",
        "priority": 8,
    },
    "international_fine_living": {
        "id": "international_fine_living",
        "name": "International Fine Living",
        "base_url": "https://www.internationalfineliving.com",
        "listings_url": "https://cpl01.ogonline.nl/api/listings",
        "type": "traditional",
        "priority": 8,
    },
    "moret": {
        "id": "moret",
        "name": "Moret Real Estate",
        "base_url": "https://moretrealestate.com",
        "listings_url": "https://moretrealestate.com/kies/kopen/",
        "type": "traditional",
        "priority": 8,
    },
    "nh_real_estate": {
        "id": "nh_real_estate",
        "name": "NH Real Estate & Associates",
        "base_url": "https://curacao-houses.com",
        "listings_url": "https://curacao-houses.com/wp-json/wp/v2/estate_property",
        "type": "traditional",
        "priority": 8,
    },
    "sunlife": {
        "id": "sunlife",
        "name": "Sunlife Real Estate",
        "base_url": "https://sunlife.realty",
        "listings_url": "https://sunlife.realty/sitemap.xml",
        "type": "traditional",
        "priority": 8,
    },
    "sunset_realtors": {
        "id": "sunset_realtors",
        "name": "Sunset Realtors",
        "base_url": "https://sunset-realtors.com",
        "listings_url": "https://sunset-realtors.com/property-sitemap.xml",
        "type": "traditional",
        "priority": 8,
    },
    "curacao_exclusive": {
        "id": "curacao_exclusive",
        "name": "Curaçao Exclusive Real Estate",
        "base_url": "https://www.curacao-exclusive-realestate.com",
        "listings_url": "https://www.curacao-exclusive-realestate.com/wp-json/wp/v2/properties",
        "type": "traditional",
        "priority": 8,
    },
    "real_estate_agency_cb": {
        "id": "real_estate_agency_cb",
        "name": "Real Estate Agency CB",
        "base_url": "https://curacao-homes.com",
        "listings_url": "https://curacao-homes.com/wp-json/wp/v2/properties",
        "type": "traditional",
        "priority": 8,
    },
    "ambiente": {
        "id": "ambiente",
        "name": "Ambiente Real Estate",
        "base_url": "https://ambienterealestate.com",
        "listings_url": "https://ambienterealestate.com/properties-sitemap.xml",
        "type": "traditional",
        "priority": 8,
    },
    "palmstone": {
        "id": "palmstone",
        "name": "Palmstone Real Estate",
        "base_url": "https://palmstone.realestate",
        "listings_url": "https://palmstone.realestate/listings/for-sale",
        "type": "traditional",
        "priority": 8,
    },
    "real_estate_caribe": {
        "id": "real_estate_caribe",
        "name": "Real Estate Caribe",
        "base_url": "https://www.realestatecaribe.com",
        "listings_url": "https://www.realestatecaribe.com/wp-json/wp/v2/property",
        "type": "traditional",
        "priority": 8,
    },
    "ruseler": {
        "id": "ruseler",
        "name": "Ruseler Makelaars",
        "base_url": "https://ruselermakelaars.com",
        "listings_url": "https://ruselermakelaars.com/wp-json/wp/v2/aanbod",
        "type": "traditional",
        "priority": 8,
    },
    "landmark": {
        "id": "landmark",
        "name": "Landmark Real Estate",
        "base_url": "https://www.landmark.cw",
        "listings_url": "https://www.landmark.cw/nl/realtime-listings/consumer",
        "type": "traditional",
        "priority": 8,
    },
    "kostabon": {
        "id": "kostabon",
        "name": "Kostabon",
        "base_url": "https://kostabon.com",
        "listings_url": "https://kostabon.com/properties-sitemap.xml",
        "type": "traditional",
        "priority": 8,
    },
    "simmer": {
        "id": "simmer",
        "name": "Simmer Real Estate",
        "base_url": "https://simmerrealestate.com",
        "listings_url": "https://simmerrealestate.com/wp-json/wp/v2/property",
        "type": "traditional",
        "priority": 8,
    },
    "top_makelaar": {
        "id": "top_makelaar",
        "name": "TOP Makelaar Curacao",
        "base_url": "https://www.topmakelaarcuracao.com",
        "listings_url": "https://www.topmakelaarcuracao.com/aanbod",
        "type": "traditional",
        "priority": 8,
    },
    "bru_de_roque": {
        "id": "bru_de_roque",
        "name": "Bru de Roque",
        "base_url": "https://bruderoque.com",
        "listings_url": "https://bruderoque.com/wp-json/directorist/v2/listings",
        "type": "traditional",
        "priority": 8,
    },
    "domicilie": {
        "id": "domicilie",
        "name": "Domicilie Real Estate",
        "base_url": "https://www.domicilie.net",
        "listings_url": "https://www.domicilie.net/wp-sitemap-posts-property-1.xml",
        "type": "traditional",
        "priority": 8,
    },
    "pricematch": {
        "id": "pricematch",
        "name": "PriceMatch Real Estate",
        "base_url": "https://pricematchrealestate.com",
        "listings_url": "https://pricematchrealestate.com/wp-sitemap-posts-property-1.xml",
        "type": "traditional",
        "priority": 8,
    },
    "curacao_homes": {
        "id": "curacao_homes",
        "name": "Curaçao Homes",
        "base_url": "https://www.curacaohomes.com",
        "listings_url": "https://www.curacaohomes.com/realestate/houses-for-sale",
        "type": "traditional",
        "priority": 8,
    },
    "curacao_real_estate_solution": {
        "id": "curacao_real_estate_solution",
        "name": "Curaçao Real Estate Solution",
        "base_url": "https://curacaorealestatesolution.com",
        "listings_url": "https://curacaorealestatesolution.com/wp-json/wp/v2/properties",
        "type": "traditional",
        "priority": 8,
    },
    "gs_realestate": {
        "id": "gs_realestate",
        "name": "GS Real Estate B.V.",
        "base_url": "https://www.gs-realestate.com",
        "listings_url": "https://www.gs-realestate.com/property-sitemap.xml",
        "type": "traditional",
        "priority": 8,
    },
    "martis_partners": {
        "id": "martis_partners",
        "name": "Martis Partners",
        "base_url": "https://martis-partners.com",
        "listings_url": "https://martis-partners.com/koopwoningen",
        "type": "traditional",
        "priority": 8,
    },
    "cur_estates": {
        "id": "cur_estates",
        "name": "Cur-Estates",
        "base_url": "https://www.cur-estates.com",
        "listings_url": "https://www.cur-estates.com/properties",
        "type": "traditional",
        "priority": 8,
    },
    "novo_casa_realty": {
        "id": "novo_casa_realty",
        "name": "Novo Casa Realty",
        "base_url": "https://novocasarealty.com",
        "listings_url": "https://novocasarealty.com/estate_property-sitemap.xml",
        "type": "traditional",
        "priority": 8,
    },
    "dmj_makelaar": {
        "id": "dmj_makelaar",
        "name": "DMJ Makelaar",
        "base_url": "https://dmjmakelaar.com",
        "listings_url": "https://dmjmakelaar.com/page-sitemap.xml",
        "type": "traditional",
        "priority": 9,
    },
    "wigbold": {
        "id": "wigbold",
        "name": "Wigbold Real Estate",
        "base_url": "https://www.wigboldrealestate.com",
        "listings_url": "https://www.wigboldrealestate.com/en/realtime-listings/consumer",
        "type": "traditional",
        "priority": 8,
    },
    "salas_real_estate": {
        "id": "salas_real_estate",
        "name": "Salas Real Estate",
        "base_url": "https://www.salasrealestate.net",
        "listings_url": "https://www.salasrealestate.net/sitemap.xml",
        "type": "traditional",
        "priority": 6,
    },
    "caribbean_evolution_realty": {
        "id": "caribbean_evolution_realty",
        "name": "Caribbean Evolution Realty",
        "base_url": "https://www.caribbeanevolutionrealty.com",
        "listings_url": "https://www.caribbeanevolutionrealty.com/index.php?rest_route=/wp/v2/properties",
        "type": "traditional",
        "priority": 8,
    },
    "vastiva": {
        "id": "vastiva",
        "name": "Vastiva",
        "base_url": "https://www.vastiva.nl",
        "listings_url": "https://www.vastiva.nl/sitemap-aanbod.xml",
        "type": "traditional",
        "priority": 6,
    },
    "curacao_houses": {
        "id": "curacao_houses",
        "name": "Curaçao Houses",
        "base_url": "https://www.curacaohouses.com",
        "listings_url": "https://www.curacaohouses.com/property-sitemap.xml",
        "type": "traditional",
        "priority": 6,
    },
}

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "Accept-Language": "nl-NL,nl;q=0.9,en;q=0.8",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
}

REQUEST_DELAY = (2, 5)  # random seconden tussen requests
MAX_RETRIES   = 3
TIMEOUT       = 30
